**Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow**

How to compute the eigenvalues and right eigenvectors of a given square array using NumPy library.

In [10]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2],
			[2, 3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right Eigen Vectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [9]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01 -1.24701000e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [11]:
import tensorflow as tf

In [12]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[6.27765  8.465221]
 [4.605569 8.253187]]




In [13]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.7777222  -0.62860805]
 [ 0.62860805 -0.7777222 ]] 

Eigen Values: 
[ 2.5551157 11.975719 ]



In [15]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[9.307316  7.0903497 5.7690153]
 [5.0759497 3.3975215 5.447535 ]
 [7.1719255 8.190127  8.284345 ]]




In [16]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[ 0.02868362 -0.79877657  0.6009437 ]
 [ 0.7926157   0.38447934  0.47321904]
 [-0.6090465   0.46274388  0.64415103]] 

Eigen Values: 
[-2.712089  2.709274 20.991999]

